# Generated by Django 5.0.1 on 2024-01-27 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Music',
        ),
    ]
